### ISSUE TITLE
Update listener error blocks plugin and some save events

### ISSUE THREAD

**Issue by rbmntjs** [typemytype/slanterRoboFontExtension#2]
Fresh boot. I try to use Slanter on a glyph. It doesn’t load. Every time I create an event – drag a node, select a window, change the glyph selection – this error pops up:

```
Traceback (most recent call last):
  File "slanter.py", line 171, in currentGlyphChanged
  File "slanter.py", line 163, in parametersChanged
  File "slanter.py", line 71, in getGlyph
  File "lib/fontObjects/robofabWrapper.pyc", line 2453, in _get_box
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/defcon/objects/glyph.py", line 197, in _get_bounds
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/defcon/objects/glyph.py", line 299, in draw
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/defcon/objects/glyph.py", line 308, in drawPoints
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/defcon/objects/component.py", line 107, in drawPoints
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/robofab/pens/adapterPens.py", line 111, in addComponent
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/pens/basePen.py", line 166, in addComponent
TypeError: 'NoneType' object has no attribute '__getitem__'
```

A similar error occurs and blocks the save action every now and then. I can’t yet tell what causes it, and can’t replicate it right now. When I do, I’ll add the error here.

**Comment by rbmntjs** [comment]
I’ve narrowed it down. It fails to run on glyphs with components in them. This is a quiet failure, except for that error message, and the observer runs without the window active, so every glyph with component I select after initialising the extension throws an error. It becomes a bit noisy in there.
